### ISSUE TITLE
Unrecognized function or variable 'fm2dc'.

### ISSUE THREAD

**Issue by OmarRasgado** [patnr/FM#3]
Hi I am trying to run the example TS_strata.m but I get the following error:

Error in fm (line 208)
			[T eFlag] = fm2dc(F,SourcePoints,dy,dx,opts.order);

Error in TS_strata (line 26)
T4 = fm(F,SPs,Dxyz,struct('implementation','C++','order',2));

I am using Matlab 2021b

**Comment by patnr** [comment]
Is that the whole error message?

**Comment by OmarRasgado** [comment]
Yes. But I solved my issued. I didn't read carefully. I just set the implementation to 'Matlab':

fm(F,SPs,Dxyz,struct('implementation','Matlab++','order',2));

Many Thanks!
