### ISSUE TITLE
Ray trace not finding the right path

### ISSUE THREAD

**Issue by OmarRasgado** [patnr/FM#4]
Hi, I am running the following code (based on TS_maze.m example).  It is a medium with varying velocity at the layers. The wavefields are calculated nicely. However, the ray trace function doesn't find  the travelled path between the source and the receiver. I am I missing something?  
The code is attached below.

`%  code source: https://github.com/patnr/FM
%% Inputs
clc; clear;
addpath('./functions');         % Add path of functions for FMM
%% Meshing
h         = 0.0041;                  % Step h
nx        = 161;                     % Depth (z) nodes #
nz        = 166;                     % Length (x) nodes #
lx        = (nx-1)*h;                % LZ length m
lz        = (nz-1)*h;                % LX Length (m)
%% Anisotropic velocity field
v0         = 1752.85;                        % Phase velocity 
matrix      = ones(nx,nz); 
th          = linspace(-180,180,nx);
alpha       = (0.329*ones(1,length(th))+ ... %Anisotropy parameter
               0.1055*cosd(th))./...
              (0.329*ones(1,length(th))+ 0.1055*ones(1,length(th)));

V           = (v0./alpha)'.*matrix;         % Velocity field
SPs         = [83;81];                       % Source
RPs         = [166;81];                     % Receiver

%% Calculations V
T1       = fm(V,SPs,[1 1],struct('implementation','Matlab','order',2));
settings = struct('useFD',1,'stepSize',2);
path1    = rayTrace(T1,SPs,RPs,settings);
%% Plot
figure
contourf(flipud(T1),'DisplayName','Wavefronts');
hold on;
plot(path1(2,:),path1(1,:),'k','LineWidth',1,'DisplayName','Ray path');
plot(RPs(1),RPs(2),'sk','MarkerFaceColor','k','MarkerSize',14,'DisplayName','Receiver')
plot(SPs(1),SPs(2),'ok','MarkerFaceColor','k','MarkerSize',18,'DisplayName','Source')
lgd = legend;
    lgd.NumColumns = 1;
    lgd.Location='southeast';
hold off;
title('Wave fronts in an anisotropic medium');

`

**Comment by patnr** [comment]
Hi!

I'm afraid I don't have the capacity to look into this right now. But let me know if you figure out the problem!
