### ISSUE TITLE
About errors from mex fm2dc.cpp util.cpp heap.cpp

### ISSUE THREAD

**Issue by Timothy-Xia** [patnr/FM#6]
Hi, Patrick! When I run CompileMexFile.m. The error shows in the following.
/home/users3/fx592/3D eikonal equation/utils.cpp: In function ‘mxArray* myCreateIntScalar()’:
/home/users3/fx592/3D eikonal equation/utils.cpp:129:67: error: cannot convert ‘int*’ to ‘const mwSize* {aka const
long unsigned int*}’ for argument ‘2’ to ‘mxArray* mxCreateNumericArray_730(mwSize, const mwSize*, mxClassID,
mxComplexity)’
   return mxCreateNumericArray(1,dimsOfAScalar,mxINT32_CLASS,mxREAL);

I revise the function into the following

mxArray * myCreateIntScalar() {
		mwSize dimsOfAScalar[2] = {1,1};
		return mxCreateNumericArray(1,dimsOfAScalar,mxINT32_CLASS,mxREAL);
}
I change int into mwSize. Finallly, I can get through it.

Could you confirm and explain this? I just want to make sure.

Thank you
Timothy

**Comment by patnr** [comment]
Hi,

Thanks for the report. Unfortunately I don't remember very much, so I cannot confirm if your fix is valid.

But the README says to use the GNU compiler (i.e. `gcc`) and I think you said you were using the "Microsoft Visual C++" compiler, so it's quite likely to be the cause. This also makes it seem likely that your fix is valid.

**Comment by Timothy-Xia** [comment]
Thank you so much. I think I figured it out. I changed to using the GUN
compiler.  Only one error (which is what I mentioned above) comes out. To
make it through, one needs to change *int* to *mwSize*.

Patrick N. Raanes ***@***.***> 于2023年4月17日周一 01:40写道：

**Comment by Timothy-Xia** [comment]
Hi, Patrick! Sorry for disturbance. I saw your raytrace subfunction, but it is only for 2D. Do you have 3D ray trace for this FMM?
